server:
  port: ${PORT:8080}
  address: 0.0.0.0

spring:
  application:
    name: jobiq-api
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true
    locations: classpath:db/migration

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      probes:
        enabled: false
      show-details: never
      show-components: never
      group:
        liveness:
          include: livenessState
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: false
    db:
      enabled: false

logging:
  level:
    root: INFO
